[package]
name = "dyndo-hls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base64 = "0.22"
dyndo-core = { path = "../dyndo-core" }
m3u8-rs = "6.0.1"
isolang = "2.4.0"
language-tags = "0.3.2"
thiserror = "2"

[dev-dependencies]
mp4-atom = "0.12"
tokio = { version = "1", features = ["macros", "rt"] }
