[package]
name = "dyndo-crypt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64 = "0.22"
quick-xml = { version = "0.41", features = ["serialize"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1", features = ["serde"] }

[lints]
workspace = true
