[package]
name = "dyndo-dash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
dash-mpd = { version = "0.20", default-features = false }
dyndo-core = { path = "../dyndo-core" }
quick-xml = { version = "0.40", features = ["serialize"] }
serde = "1"
thiserror = "2"

[dev-dependencies]
mp4-atom = "0.12"
tokio = { version = "1", features = ["macros", "rt"] }
